using TDSPro.DAL.Models;
using System.Text;

namespace TDSPro.DAL
{
    /// <summary>
    /// Generates a print-ready HTML paper return for Form 26Q / 24Q.
    /// Open in browser → Ctrl+P → Save as PDF.
    /// </summary>
    public static class PaperReturnGenerator
    {
        public static string Generate(ReturnData d, string outputPath)
        {
            var h   = d.Header;
            var sb  = new StringBuilder();
            var now = DateTime.Now.ToString("dd-MM-yyyy HH:mm");

            sb.Append($@"<!DOCTYPE html>
<html lang=""en"">
<head>
<meta charset=""UTF-8"">
<title>Paper Return — {h.FormType} {h.FinancialYear} {h.Quarter}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Arial, sans-serif; font-size: 9pt; color: #000; background: #fff; }}
  @page {{ size: A4; margin: 12mm 10mm; }}
  @media print {{ .no-print {{ display: none !important; }} }}

  .no-print {{
    position: fixed; top: 12px; right: 16px; z-index: 999;
    display: flex; gap: 8px;
  }}
  .btn {{
    padding: 8px 18px; border: none; border-radius: 4px; cursor: pointer;
    font-size: 12px; font-weight: 600;
  }}
  .btn-print {{ background: #1565C0; color: #fff; }}
  .btn-dl    {{ background: #2e7d32; color: #fff; }}

  .page-header {{
    text-align: center; border-bottom: 2px solid #000; padding-bottom: 6px; margin-bottom: 8px;
  }}
  .page-header h2 {{ font-size: 13pt; font-weight: bold; }}
  .page-header h3 {{ font-size: 10pt; font-weight: normal; margin-top: 2px; }}
  .watermark {{
    color: #888; font-size: 8pt; margin-top: 2px;
  }}

  .info-grid {{
    display: grid; grid-template-columns: 1fr 1fr; gap: 0;
    border: 1px solid #000; margin-bottom: 8px;
  }}
  .info-cell {{
    padding: 3px 6px; border-right: 1px solid #ccc; border-bottom: 1px solid #ccc;
    font-size: 8pt;
  }}
  .info-cell:nth-child(even) {{ border-right: none; }}
  .info-label {{ font-size: 7pt; color: #555; display: block; }}
  .info-value {{ font-weight: 600; }}

  .section-title {{
    background: #1565C0; color: #fff; padding: 3px 8px;
    font-size: 9pt; font-weight: bold; margin: 8px 0 0 0;
  }}

  table {{
    width: 100%; border-collapse: collapse; font-size: 7.5pt; margin-bottom: 8px;
  }}
  th {{
    background: #e3f2fd; border: 1px solid #aaa; padding: 3px 4px;
    text-align: center; font-weight: bold;
  }}
  td {{
    border: 1px solid #ccc; padding: 2px 4px; text-align: left;
  }}
  td.num {{ text-align: right; }}
  tr:nth-child(even) td {{ background: #fafafa; }}
  .total-row td {{ background: #e8f5e9; font-weight: bold; border-top: 2px solid #000; }}

  .summary-box {{
    border: 1px solid #000; padding: 6px 10px; margin-bottom: 8px;
    display: grid; grid-template-columns: repeat(4, 1fr); gap: 4px;
  }}
  .kpi {{ text-align: center; }}
  .kpi-label {{ font-size: 7pt; color: #555; }}
  .kpi-value {{ font-size: 11pt; font-weight: bold; color: #1565C0; }}

  .sign-block {{
    margin-top: 20px; display: grid; grid-template-columns: 1fr 1fr;
    gap: 20px; font-size: 8pt;
  }}
  .sign-line {{
    border-top: 1px solid #000; margin-top: 30px; padding-top: 4px; text-align: center;
  }}
  .footer {{
    text-align: center; font-size: 7pt; color: #888;
    border-top: 1px solid #ccc; margin-top: 12px; padding-top: 4px;
  }}
</style>
</head>
<body>

<div class=""no-print"">
  <button class=""btn btn-print"" onclick=""window.print()"">🖨 Print / Save PDF</button>
  <button class=""btn btn-dl"" onclick=""downloadHtml()"">⬇ Download HTML</button>
</div>

<div class=""page-header"">
  <h2>FORM {h.FormType} — TDS RETURN</h2>
  <h3>Statement of Tax Deducted at Source — {h.Quarter} · FY {h.FinancialYear}</h3>
  <div class=""watermark"">Generated by TDS Pro · {now} · FOR REFERENCE ONLY — Upload FVU file to TRACES/TIN</div>
</div>

<div class=""info-grid"">
  <div class=""info-cell""><span class=""info-label"">Deductor Name</span><span class=""info-value"">{Esc(h.DeductorName)}</span></div>
  <div class=""info-cell""><span class=""info-label"">TAN</span><span class=""info-value"">{Esc(h.TanOfDeductor)}</span></div>
  <div class=""info-cell""><span class=""info-label"">PAN</span><span class=""info-value"">{Esc(h.PanOfDeductor)}</span></div>
  <div class=""info-cell""><span class=""info-label"">Deductor Type</span><span class=""info-value"">{Esc(h.DeductorType)}</span></div>
  <div class=""info-cell""><span class=""info-label"">Address</span><span class=""info-value"">{Esc(h.DeductorAddress)}, {Esc(h.DeductorCity)} — {Esc(h.DeductorPin)}</span></div>
  <div class=""info-cell""><span class=""info-label"">State</span><span class=""info-value"">{Esc(h.DeductorState)}</span></div>
  <div class=""info-cell""><span class=""info-label"">Responsible Person</span><span class=""info-value"">{Esc(h.ResponsibleName)}</span></div>
  <div class=""info-cell""><span class=""info-label"">Designation / PAN</span><span class=""info-value"">{Esc(h.Designation)} / {Esc(h.ResponsiblePan)}</span></div>
  <div class=""info-cell""><span class=""info-label"">Filing Date</span><span class=""info-value"">{h.FilingDate:dd-MM-yyyy}</span></div>
  <div class=""info-cell""><span class=""info-label"">Return Type</span><span class=""info-value"">{(h.IsCorrection ? "CORRECTION" : "ORIGINAL")}</span></div>
</div>

<div class=""summary-box"">
  <div class=""kpi""><div class=""kpi-label"">Total Challans</div><div class=""kpi-value"">{d.Challans.Count}</div></div>
  <div class=""kpi""><div class=""kpi-label"">Total Deductees</div><div class=""kpi-value"">{d.Deductees.Count}</div></div>
  <div class=""kpi""><div class=""kpi-label"">Gross Amount Paid</div><div class=""kpi-value"">₹{d.TotalAmountPaid:N0}</div></div>
  <div class=""kpi""><div class=""kpi-label"">Total TDS Deducted</div><div class=""kpi-value"">₹{d.TotalTdsDeducted:N0}</div></div>
</div>
");

            // ── Challan table ──────────────────────────────────────────────────
            sb.Append(@"<div class=""section-title"">PART A — CHALLAN DETAILS</div>
<table>
<thead><tr>
  <th>Sl.</th><th>BSR Code</th><th>Challan Date</th><th>Challan No.</th>
  <th>Section</th><th style=""text-align:right"">TDS Deposited (₹)</th>
  <th style=""text-align:right"">Surcharge (₹)</th><th style=""text-align:right"">Cess (₹)</th>
  <th style=""text-align:right"">Interest (₹)</th><th style=""text-align:right"">Total (₹)</th>
  <th>Deductees</th>
</tr></thead><tbody>");

            double cTds = 0, cSur = 0, cCess = 0, cInt = 0, cTot = 0;
            foreach (var c in d.Challans)
            {
                cTds += c.TdsDeposited; cSur += c.Surcharge; cCess += c.Cess;
                cInt += c.Interest;     cTot += c.TotalDeposited;
                sb.Append($@"<tr>
  <td class=""num"">{c.SlNo}</td><td>{Esc(c.BsrCode)}</td>
  <td>{c.ChallanDate:dd-MM-yyyy}</td><td>{Esc(c.ChallanNo)}</td>
  <td>{Esc(c.Section)}</td>
  <td class=""num"">{c.TdsDeposited:N2}</td>
  <td class=""num"">{c.Surcharge:N2}</td>
  <td class=""num"">{c.Cess:N2}</td>
  <td class=""num"">{c.Interest:N2}</td>
  <td class=""num"">{c.TotalDeposited:N2}</td>
  <td class=""num"">{c.NoOfDeductees}</td>
</tr>");
            }
            sb.Append($@"<tr class=""total-row"">
  <td colspan=""5"">TOTAL</td>
  <td class=""num"">{cTds:N2}</td>
  <td class=""num"">{cSur:N2}</td>
  <td class=""num"">{cCess:N2}</td>
  <td class=""num"">{cInt:N2}</td>
  <td class=""num"">{cTot:N2}</td>
  <td class=""num"">{d.Challans.Sum(c => c.NoOfDeductees)}</td>
</tr></tbody></table>");

            // ── Deductee table ─────────────────────────────────────────────────
            sb.Append(@"<div class=""section-title"">PART B — DEDUCTEE DETAILS</div>
<table>
<thead><tr>
  <th>Sl.</th><th>PAN</th><th>Name</th><th>Section</th><th>Date</th>
  <th style=""text-align:right"">Amount Paid (₹)</th>
  <th style=""text-align:right"">TDS Deducted (₹)</th>
  <th style=""text-align:right"">TDS Deposited (₹)</th>
  <th style=""text-align:right"">Rate %</th>
  <th>Challan</th>
</tr></thead><tbody>");

            double dAmt = 0, dDed = 0, dDep = 0;
            foreach (var e in d.Deductees)
            {
                dAmt += e.AmountPaid; dDed += e.TdsDeducted; dDep += e.TdsDeposited;
                sb.Append($@"<tr>
  <td class=""num"">{e.SlNo}</td>
  <td>{Esc(e.Pan)}</td><td>{Esc(e.Name)}</td>
  <td>{Esc(e.Section)}</td><td>{e.PaymentDate:dd-MM-yyyy}</td>
  <td class=""num"">{e.AmountPaid:N2}</td>
  <td class=""num"">{e.TdsDeducted:N2}</td>
  <td class=""num"">{e.TdsDeposited:N2}</td>
  <td class=""num"">{e.Rate:N2}</td>
  <td>{Esc(e.BsrCode)}/{Esc(e.ChallanNo)}</td>
</tr>");
            }
            sb.Append($@"<tr class=""total-row"">
  <td colspan=""5"">TOTAL</td>
  <td class=""num"">{dAmt:N2}</td>
  <td class=""num"">{dDed:N2}</td>
  <td class=""num"">{dDep:N2}</td>
  <td colspan=""2""></td>
</tr></tbody></table>");

            // ── Verification / signature block ─────────────────────────────────
            sb.Append($@"
<div class=""sign-block"">
  <div>
    <b>Verification</b><br/>
    I, <u>{Esc(h.ResponsibleName)}</u> ({Esc(h.Designation)}), do hereby certify that all the
    particulars furnished in this statement are correct and complete.
    <div class=""sign-line"">Signature &amp; Seal of Deductor</div>
  </div>
  <div>
    <b>Filing Details</b><br/>
    Form: {h.FormType} &nbsp;·&nbsp; Quarter: {h.Quarter} &nbsp;·&nbsp; FY: {h.FinancialYear}<br/>
    TAN: {Esc(h.TanOfDeductor)} &nbsp;·&nbsp; PAN: {Esc(h.PanOfDeductor)}<br/>
    Place: _________________ &nbsp; Date: _________________
    <div class=""sign-line"">Date &amp; Place of Verification</div>
  </div>
</div>

<div class=""footer"">
  This is a computer-generated paper return. File the validated .fvu file at https://www.tin-nsdl.com or https://incometax.gov.in
  &nbsp;·&nbsp; TDS Pro v2.0 &nbsp;·&nbsp; Generated: {now}
</div>

<script>
function downloadHtml() {{
  var a = document.createElement('a');
  a.href = 'data:text/html;charset=utf-8,' + encodeURIComponent(document.documentElement.outerHTML);
  a.download = '{h.FormType}_{h.TanOfDeductor}_{h.FinancialYear.Replace("-","")}_Paper_{h.Quarter}.html';
  a.click();
}}
</script>
</body></html>");

            var html = sb.ToString();
            File.WriteAllText(outputPath, html, Encoding.UTF8);
            return outputPath;
        }

        static string Esc(string? s) => System.Net.WebUtility.HtmlEncode(s ?? "");
    }
}
